from typing import Any, Protocol, runtime_checkable

from TaskQueue.job import Job


@runtime_checkable
class Backend(Protocol):
    async def enqueue(self, job: Job) -> None: ...
    async def claim(self) -> Job: ...
    async def get_job(self, job_id: str) -> Job: ...
    async def store_result(self, job_id: str, result: Any) -> None: ...
    async def store_error(self, job_id: str, error: str) -> None: ...
    async def wait_for(self, job_id: str) -> None: ...
